wandb_version: 1

bidirectional:
  value: 1
cell_type_decoder:
  value: LSTM
cell_type_encoder:
  value: GRU
dropout:
  value: 0
hidden_layer_size:
  value: 128
input_embedding_size:
  value: 256
num_decoder_layers:
  value: 3
num_encoder_layers:
  value: 4
teacher_forcing:
  value: 1
