wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1682297941.021081
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 17
      - 23
      - 37
      4: 3.9.6
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
bidirectional:
  desc: null
  value: 0
cell_type:
  desc: null
  value: GRU
dropout:
  desc: null
  value: 0.2
hidden_layer_size:
  desc: null
  value: 64
input_embedding_size:
  desc: null
  value: 128
num_decoder_layers:
  desc: null
  value: 1
num_encoder_layers:
  desc: null
  value: 2
teacher_forcing:
  desc: null
  value: 0.5
