wandb_version: 1

batch_size:
  value: 128
bidirectional:
  value: 1
cell_type_decoder:
  value: GRU
cell_type_encoder:
  value: LSTM
dropout:
  value: 0.3
hidden_layer_size:
  value: 32
input_embedding_size:
  value: 512
num_decoder_layers:
  value: 4
num_encoder_layers:
  value: 4
teacher_forcing:
  value: 1
