wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1683912081.024878
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 17
      - 23
      - 37
      4: 3.9.6
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 16
bidirectional:
  desc: null
  value: 0
cell_type_decoder:
  desc: null
  value: RNN
cell_type_encoder:
  desc: null
  value: LSTM
dropout:
  desc: null
  value: 0.2
hidden_layer_size:
  desc: null
  value: 64
input_embedding_size:
  desc: null
  value: 1024
num_decoder_layers:
  desc: null
  value: 5
num_encoder_layers:
  desc: null
  value: 5
teacher_forcing:
  desc: null
  value: 0.75
