wandb_version: 1

bidirectional:
  value: 0
cell_type:
  value: LSTM
dropout:
  value: 0.3
hidden_layer_size:
  value: 128
input_embedding_size:
  value: 128
num_decoder_layers:
  value: 1
num_encoder_layers:
  value: 1
