wandb_version: 1

bidirectional:
  value: 0
cell_type:
  value: LSTM
dropout:
  value: 0.2
hidden_layer_size:
  value: 64
input_embedding_size:
  value: 32
num_decoder_layers:
  value: 1
num_encoder_layers:
  value: 3
teacher_forcing:
  value: 0.5
