wandb_version: 1

batch_size:
  value: 16
bidirectional:
  value: 0
cell_type_decoder:
  value: RNN
cell_type_encoder:
  value: RNN
dropout:
  value: 0.3
hidden_layer_size:
  value: 32
input_embedding_size:
  value: 512
num_decoder_layers:
  value: 6
num_encoder_layers:
  value: 6
teacher_forcing:
  value: 0
