wandb_version: 1

bidirectional:
  value: 0
cell_type:
  value: LSTM
dropout:
  value: 0.2
hidden_layer_size:
  value: 128
input_embedding_size:
  value: 32
num_decoder_layers:
  value: 2
num_encoder_layers:
  value: 1
teacher_forcing:
  value: 0.75
