wandb_version: 1

bidirectional:
  value: 0
cell_type:
  value: GRU
dropout:
  value: 0
hidden_layer_size:
  value: 64
input_embedding_size:
  value: 128
num_decoder_layers:
  value: 3
num_encoder_layers:
  value: 1
teacher_forcing:
  value: 0.75
