wandb_version: 1

bidirectional:
  value: 0
cell_type:
  value: RNN
dropout:
  value: 0
hidden_layer_size:
  value: 128
input_embedding_size:
  value: 64
num_decoder_layers:
  value: 2
num_encoder_layers:
  value: 2
teacher_forcing:
  value: 0.75
